### ISSUE TITLE
mouse and toolbar improvements

### ISSUE THREAD

**Issue by andrejv** [wxMaxima-developers/wxmaxima#155]
Converted from [SourceForge issue 2814129](http://sourceforge.net/support/tracker.php?aid=2814129), submitted by dougedmunds

These are on my wish-list:

- [ ]  mouse: add right-click functionality when on a 'horizontal line' for pasting (after using mouse to select all  and copy some other entry)
- [x] toolbar: add a "select all" button and a "paste" button to the toolbar
- [ ] mouse: add single-click combination for "select all then copy" to right click context menu
- [ ] mouse: double-click that selects the entire input.  Suggested locations: double clicking on the system prompt ">>" ;   the space just to the right of >>; after the last input character. This would also work on the (%i##) if the expression has been evaluated, but do not include the input number (%i##) part  of the line.  
- [ ] mouse: similar to the preceding item, but for output after expression evaluated.  Double-click that selects entire output, without the output number (%o###) part of the line
- [ ] toolbar: a 'see input as xml' button.  This would show the ascii input as xml, but without doing any calculations.  The effect is similar to doing this sequence of steps: 1. simp:false; 2. <enter your expression>; 3. <shift-enter to evaluate>; 4. simp:true.  
   However, note that depending on the packages loaded, I find that simp:false cannot always be set.

**Comment by gunterkoenigsmann** [comment]
We have the xml monitor now. For the rest this would deviate from the standard user experience. Even if it can be used efficiently that would cause more trouble than it would help
